name: ente_auth
description: ente two-factor authenticator
version: 2.0.34+234
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  adaptive_theme: ^3.1.0 # done
  app_links: ^3.5.0
  archive: ^3.3.7
  base32: ^2.1.3
  bip39: ^1.0.6 #done
  bloc: ^8.1.2
  clipboard: ^0.1.3
  collection: # dart
  confetti: ^0.7.0
  connectivity_plus: ^5.0.2
  convert: ^3.1.1
  desktop_webview_window:
    git:
      url: https://github.com/MixinNetwork/flutter-plugins
      path: packages/desktop_webview_window
  device_info_plus: ^9.1.1
  dio: ^5.4.0
  dotted_border: ^2.0.0+2
  email_validator: ^2.0.1
  ente_crypto_dart:
    git:
      url: https://github.com/ente-io/ente_crypto_dart.git
  event_bus: ^2.0.0
  expandable: ^5.0.1
  expansion_tile_card: ^3.0.0
  ffi: ^2.1.0
  file_picker: ^6.1.1
  # https://github.com/incrediblezayed/file_saver/issues/86
  file_saver: ^0.2.9
  fixnum: ^1.1.0
  fk_user_agent: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_displaymode: ^0.6.0
  flutter_email_sender: ^6.0.2
  flutter_inappwebview: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_local_authentication: ^1.2.0
  flutter_local_notifications: ^16.3.1+1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.13
  flutter_secure_storage: ^9.0.0
  flutter_slidable: ^3.0.1
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.5
  fluttertoast: ^8.1.1
  google_nav_bar: ^5.0.5 #supported
  http: ^1.1.0
  intl: ^0.18.0
  json_annotation: ^4.5.0
  local_auth: ^2.1.7

  local_auth_android: ^1.0.31
  local_auth_ios: ^1.1.3
  logging: ^1.0.1
  modal_bottom_sheet: ^3.0.0-pre
  move_to_background: ^1.0.2
  open_filex: ^4.3.2
  otp: ^3.1.1
  package_info_plus: ^4.1.0
  password_strength: ^0.2.0
  path: ^1.8.3
  path_provider: ^2.0.11
  pinput: ^3.0.1
  pointycastle: ^3.7.3
  privacy_screen: ^0.0.6
  protobuf: ^3.0.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  sentry: ^7.9.0
  sentry_flutter: ^7.9.0
  share_plus: ^7.2.1
  shared_preferences: ^2.0.5
  sqflite:
    git:
      url: https://github.com/tekartik/sqflite
      path: sqflite
  sqflite_common_ffi: ^2.3.0+4
  sqlite3: ^2.1.0
  sqlite3_flutter_libs: ^0.5.19+1
  step_progress_indicator: ^1.0.2
  styled_text: ^8.1.0
  tuple: ^2.0.0
  url_launcher: ^6.1.5
  uuid: ^4.2.2
  win32: ^5.1.1

dependency_overrides:
  flutter_secure_storage_linux:
    git:
      url: https://github.com/prateekmedia/flutter_secure_storage.git
      ref: patch-1
      path: flutter_secure_storage_linux
dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  lints: ^3.0.0
  mocktail: ^1.0.3

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  generate: true

  # https://docs:flutter:dev/development/ui/assets-and-images:
  assets:
    - assets/
    - assets/simple-icons/icons/
    - assets/simple-icons/_data/
    - assets/custom-icons/icons/
    - assets/custom-icons/_data/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Medium.ttf
        - asset: fonts/Inter-Light.ttf
        - asset: fonts/Inter-SemiBold.ttf
        - asset: fonts/Inter-Bold.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf

flutter_icons:
  android: "launcher_icon"
  adaptive_icon_foreground: "assets/icon-light-adaptive-fg.png"
  adaptive_icon_background: "#ffffff"
  ios: true
  image_path: "assets/icon-light.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: assets/splash-screen-light.png
  image_dark: assets/splash-screen-dark.png
  android_fullscreen: true
  android_gravity: center
  ios_content_mode: center
